/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        mono:    ['IBM Plex Mono', 'monospace'],
        sans:    ['IBM Plex Sans', 'sans-serif'],
        serif:   ['IBM Plex Serif', 'serif'],
        display: ['IBM Plex Mono', 'monospace'],
        inter:   ['IBM Plex Sans', 'sans-serif'],
      },
      colors: {
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        card:        { DEFAULT: 'hsl(var(--card))',        foreground: 'hsl(var(--card-foreground))' },
        popover:     { DEFAULT: 'hsl(var(--popover))',     foreground: 'hsl(var(--popover-foreground))' },
        primary:     { DEFAULT: 'hsl(var(--primary))',     foreground: 'hsl(var(--primary-foreground))' },
        secondary:   { DEFAULT: 'hsl(var(--secondary))',   foreground: 'hsl(var(--secondary-foreground))' },
        muted:       { DEFAULT: 'hsl(var(--muted))',       foreground: 'hsl(var(--muted-foreground))' },
        accent:      { DEFAULT: 'hsl(var(--accent))',      foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border:  'hsl(var(--border))',
        input:   'hsl(var(--input))',
        ring:    'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT:             'hsl(var(--sidebar-background))',
          foreground:          'hsl(var(--sidebar-foreground))',
          primary:             'hsl(var(--sidebar-primary))',
          'primary-foreground':'hsl(var(--sidebar-primary-foreground))',
          accent:              'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border:              'hsl(var(--sidebar-border))',
          ring:                'hsl(var(--sidebar-ring))',
        },
        /* Design system direct tokens */
        'ds-base':    'hsl(var(--background))',
        'ds-surface': 'hsl(var(--card))',
        'ds-surface2':'hsl(var(--secondary))',
        'ds-surface3':'hsl(var(--muted))',
        'ds-border':  'hsl(var(--border))',
        'ds-border-m':'hsl(var(--input))',
        'ds-black':   'hsl(var(--background))',
        'ds-beige':   '#8C8478',
        'ds-beige-lt':'rgba(140,132,120,0.15)',
        'ds-up':      '#34D399',
        'ds-up-bg':   'rgba(52,211,153,0.10)',
        'ds-dn':      '#F87171',
        'ds-dn-bg':   'rgba(248,113,113,0.10)',
      },
      borderRadius: {
        'none': '0',
        'sm':   '3px',
        DEFAULT:'6px',
        'md':   '6px',
        'lg':   '10px',
        'xl':   '16px',
        '2xl':  '20px',
        'full': '9999px',
      },
      boxShadow: {
        'sm':  '0 1px 3px rgba(0,0,0,.4), 0 1px 2px rgba(0,0,0,.3)',
        DEFAULT:'0 4px 16px rgba(0,0,0,.5), 0 2px 4px rgba(0,0,0,.3)',
        'md':  '0 4px 16px rgba(0,0,0,.5), 0 2px 4px rgba(0,0,0,.3)',
        'lg':  '0 8px 32px rgba(0,0,0,.6), 0 4px 8px rgba(0,0,0,.4)',
        'glow':'0 0 20px rgba(52,211,153,0.15)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'ticker':         { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        'fade-up':        { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'pulse-slow':     { '0%,100%': { opacity: '1' }, '50%': { opacity: '.5' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'ticker':         'ticker 40s linear infinite',
        'fade-up':        'fade-up 0.3s ease forwards',
        'pulse-slow':     'pulse-slow 3s ease-in-out infinite',
      },
    },
  },
  safelist: [
    // Sentiment/impact dynamic colors
    'text-emerald-400', 'text-red-400', 'text-yellow-400', 'text-orange-400', 'text-slate-400',
    'bg-red-500/15', 'bg-orange-500/15', 'bg-yellow-500/15', 'bg-slate-500/15',
    'border-red-500/20', 'border-orange-500/20', 'border-yellow-500/20', 'border-slate-500/20',
  ],
  plugins: [require("tailwindcss-animate")],
}
